-- Q1 What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue FROM customer_behavior 
GROUP BY gender;

-- Q2 Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount FROM customer_behavior
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_behavior);

-- Q3 Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating" FROM customer_behavior
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4 Compare the average purchase amount between standard and express shipping.
SELECT shipping_type,ROUND(AVG(purchase_amount),2) FROM customer_behavior
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) as total_customers, ROUND(AVG(purchase_amount),2) AS avg_spend, ROUND(SUM(purchase_amount),2) AS total_revenue FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- Q6 Which 5 Products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(AVG(discount_applied = 'Yes') * 100, 2) AS discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7 Segment customers into New, Returning, and loyal based on their total number of previous  purchases, and show the count of each segment?
 WITH customer_type as (
     SELECT customer_id,previous_purchases, 
     CASE WHEN previous_purchases = 1 THEN 'New' 
          WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' ELSE 'Loyal' END AS customer_segment 
          FROM customer_behavior 
	)

SELECT customer_segment, COUNT(*) as "Number of customer" 
FROM customer_type 
GROUP BY customer_segment;
 
 -- Q8 What are the top 3 most purchased products within each category? 
 SELECT t.category, t.item_purchased, t.total_orders 
 FROM ( 
       SELECT category, item_purchased, COUNT(*) AS total_orders 
       FROM customer_behavior GROUP BY category, item_purchased 
       ) t 
WHERE ( 
	   SELECT COUNT(*) 
       FROM ( 
			SELECT category, item_purchased, COUNT(*) AS cnt 
            FROM customer_behavior 
            GROUP BY category, item_purchased 
            ) t2 
		WHERE t2.category = t.category AND t2.cnt > t.total_orders ) < 3 
        ORDER BY t.category, t.total_orders DESC;
 
 -- Q9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe? 
 SELECT subscription_status, COUNT(customer_id) AS repeat_buyers 
 FROM customer_behavior 
 WHERE previous_purchases > 5 
 GROUP BY subscription_status;
 
 -- Q10 What is the revenue contribution of each age group?
 SELECT age_group, SUM(purchase_amount) AS total_revenue 
 FROM customer_behavior 
 GROUP BY age_group 
 ORDER BY total_revenue DESC;